server:
  port: ${PORT:0}   # Railway asigna puerto automáticamente

spring:
  application:
    name: ms-gateway

eureka:
  client:
    service-url:
      defaultZone: https://${RAILWAY_PUBLIC_DOMAIN:ms-eureka.up.railway.app}/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    instance-id: ${spring.application.name}:${random.value}
    prefer-ip-address: false

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true    # Habilita rutas automáticas vía Eureka
